name: CI-Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_lib:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout Dagger Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Compile Dagger Library
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON .
        make |& tee build-output.txt ; ( exit ${PIPESTATUS[0]} )

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: build-output-failure
        path: build-output.txt
        retention-days: 5
        
    - name: Test the library
      run: ctest -VV -O test-output.txt
      
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test-output-failure
        path: test-output.txt
        retention-days: 5

  build_exec:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout Dagger Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Compile Dagger Example Executable
      working-directory: ./app
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON .
        make |& tee build-output2.txt ; ( exit ${PIPESTATUS[0]} )

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: build-output2-failure
        path: ./app/build-output2.txt
        retention-days: 5
