name: CI-Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y valgrind
           
    - name: Checkout DragLibReader Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Compile DragLibReader Library
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release .
        make |& tee build-output.txt ; ( exit ${PIPESTATUS[0]} )
    
    - uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: build-output.txt
        
    # - name: Test Almost
    #   run: ctest -VV -O test-output.txt
      
    # - uses: actions/upload-artifact@v2
    #   if: failure()
    #   with:
    #     name: test-output-failure
    #     path: test-output.txt
    
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: test-output
    #     path: test-output.txt

    # - name: Compile DragLibReader Example Executable
    #   working-directory: ./app
    #   run: |
    #     cmake -DCMAKE_BUILD_TYPE=Release .
    #     make |& tee build-output2.txt ; ( exit ${PIPESTATUS[0]} )
    
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: build-output2
    #     path: build-output2.txt
